### ISSUE TITLE
The app not working in production mode

### ISSUE THREAD

**Issue by EnziinSystem** [gbarillot/rails-vue-demo-app#5]
The app not working in production mode.

```
RAILS_ENV=production bundle exec rake secret
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production bundle exec rake db:seed
RAILS_ENV=production bundle exec rake assets:precompile
```

Start puma.

`bundle exec puma -e production`

Error:

```
I, [2018-06-21T04:45:39.354065 #1905]  INFO -- : [764703a2-6de4-484b-9a3e-62bfbd2e504d] Started GET "/" for 172.17.0.1 at 2018-06-21 04:45:39 +0000
I, [2018-06-21T04:45:39.363789 #1905]  INFO -- : [764703a2-6de4-484b-9a3e-62bfbd2e504d] Processing by ApplicationController#index as HTML
I, [2018-06-21T04:45:39.363924 #1905]  INFO -- : [764703a2-6de4-484b-9a3e-62bfbd2e504d]   Parameters: {"locale"=>"en"}
I, [2018-06-21T04:45:39.366996 #1905]  INFO -- : [764703a2-6de4-484b-9a3e-62bfbd2e504d]   Rendering application.html.erb
I, [2018-06-21T04:45:39.372743 #1905]  INFO -- : [764703a2-6de4-484b-9a3e-62bfbd2e504d]   Rendered application.html.erb (5.6ms)
I, [2018-06-21T04:45:39.373032 #1905]  INFO -- : [764703a2-6de4-484b-9a3e-62bfbd2e504d] Completed 200 OK in 9ms (Views: 8.6ms)
I, [2018-06-21T04:45:39.439561 #1905]  INFO -- : [e75fc345-769e-43eb-aa33-952f20c5006b] Started GET "/assets/application-a7d87bae96496b796910b3d5c577d6119212011646d1bab4cde0d7d614130355.css" for 172.17.0.1 at 2018-06-21 04:45:39 +0000
I, [2018-06-21T04:45:39.440840 #1905]  INFO -- : [e75fc345-769e-43eb-aa33-952f20c5006b] Processing by ApplicationController#index as CSS
I, [2018-06-21T04:45:39.441018 #1905]  INFO -- : [e75fc345-769e-43eb-aa33-952f20c5006b]   Parameters: {"locale"=>"en", "path"=>"assets/application-a7d87bae96496b796910b3d5c577d6119212011646d1bab4cde0d7d614130355.css"}
I, [2018-06-21T04:45:39.442974 #1905]  INFO -- : [e75fc345-769e-43eb-aa33-952f20c5006b] Completed 500 Internal Server Error in 2ms
F, [2018-06-21T04:45:39.444536 #1905] FATAL -- : [e75fc345-769e-43eb-aa33-952f20c5006b]   
F, [2018-06-21T04:45:39.445146 #1905] FATAL -- : [e75fc345-769e-43eb-aa33-952f20c5006b] ActionView::MissingTemplate (Missing template /application with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/home/developer/websites/rails-vue-demo-app/app/views"
  * "/usr/local/rvm/gems/ruby-2.5.1/gems/devise-4.4.3/app/views"
  * "/usr/local/rvm/gems/ruby-2.5.1/gems/kaminari-core-1.1.1/app/views"
):
F, [2018-06-21T04:45:39.445213 #1905] FATAL -- : [e75fc345-769e-43eb-aa33-952f20c5006b]   
F, [2018-06-21T04:45:39.445292 #1905] FATAL -- : [e75fc345-769e-43eb-aa33-952f20c5006b] app/controllers/application_controller.rb:5:in `index'
I, [2018-06-21T04:45:39.443448 #1905]  INFO -- : [822ada3b-2e2e-47fe-a147-6cafd0726afb] Started GET "/assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js" for 172.17.0.1 at 2018-06-21 04:45:39 +0000
I, [2018-06-21T04:45:39.446286 #1905]  INFO -- : [822ada3b-2e2e-47fe-a147-6cafd0726afb] Processing by ApplicationController#index as */*
I, [2018-06-21T04:45:39.446407 #1905]  INFO -- : [822ada3b-2e2e-47fe-a147-6cafd0726afb]   Parameters: {"locale"=>"en", "path"=>"assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js"}
I, [2018-06-21T04:45:39.445060 #1905]  INFO -- : [ac9b1ab3-5a30-4fa8-93b9-fd471480e8b5] Started GET "/packs/application-f73d5ebd30f5d7783872.js" for 172.17.0.1 at 2018-06-21 04:45:39 +0000
I, [2018-06-21T04:45:39.451154 #1905]  INFO -- : [ac9b1ab3-5a30-4fa8-93b9-fd471480e8b5] Processing by ApplicationController#index as */*
I, [2018-06-21T04:45:39.451335 #1905]  INFO -- : [ac9b1ab3-5a30-4fa8-93b9-fd471480e8b5]   Parameters: {"locale"=>"en", "path"=>"packs/application-f73d5ebd30f5d7783872.js"}
I, [2018-06-21T04:45:39.451995 #1905]  INFO -- : [ac9b1ab3-5a30-4fa8-93b9-fd471480e8b5]   Rendering application.html.erb
I, [2018-06-21T04:45:39.453515 #1905]  INFO -- : [ac9b1ab3-5a30-4fa8-93b9-fd471480e8b5]   Rendered application.html.erb (1.4ms)
I, [2018-06-21T04:45:39.453768 #1905]  INFO -- : [ac9b1ab3-5a30-4fa8-93b9-fd471480e8b5] Completed 200 OK in 2ms (Views: 1.9ms)
I, [2018-06-21T04:45:39.451555 #1905]  INFO -- : [822ada3b-2e2e-47fe-a147-6cafd0726afb]   Rendering application.html.erb
I, [2018-06-21T04:45:39.456522 #1905]  INFO -- : [822ada3b-2e2e-47fe-a147-6cafd0726afb]   Rendered application.html.erb (1.8ms)
I, [2018-06-21T04:45:39.457125 #1905]  INFO -- : [822ada3b-2e2e-47fe-a147-6cafd0726afb] Completed 200 OK in 10ms (Views: 10.1ms)
I, [2018-06-21T04:45:39.488301 #1905]  INFO -- : [68885701-d44e-46f9-ae1f-7093c702e4dc] Started GET "/assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js" for 172.17.0.1 at 2018-06-21 04:45:39 +0000
I, [2018-06-21T04:45:39.489039 #1905]  INFO -- : [68885701-d44e-46f9-ae1f-7093c702e4dc] Processing by ApplicationController#index as */*
I, [2018-06-21T04:45:39.489126 #1905]  INFO -- : [68885701-d44e-46f9-ae1f-7093c702e4dc]   Parameters: {"locale"=>"en", "path"=>"assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js"}
I, [2018-06-21T04:45:39.489822 #1905]  INFO -- : [68885701-d44e-46f9-ae1f-7093c702e4dc]   Rendering application.html.erb
I, [2018-06-21T04:45:39.491364 #1905]  INFO -- : [68885701-d44e-46f9-ae1f-7093c702e4dc]   Rendered application.html.erb (1.4ms)
I, [2018-06-21T04:45:39.491701 #1905]  INFO -- : [68885701-d44e-46f9-ae1f-7093c702e4dc] Completed 200 OK in 2ms (Views: 2.1ms)
I, [2018-06-21T04:45:39.503940 #1905]  INFO -- : [53cc03e4-c93a-4572-b904-73acf7f9415e] Started GET "/packs/application-f73d5ebd30f5d7783872.js" for 172.17.0.1 at 2018-06-21 04:45:39 +0000
I, [2018-06-21T04:45:39.505061 #1905]  INFO -- : [53cc03e4-c93a-4572-b904-73acf7f9415e] Processing by ApplicationController#index as */*
I, [2018-06-21T04:45:39.505212 #1905]  INFO -- : [53cc03e4-c93a-4572-b904-73acf7f9415e]   Parameters: {"locale"=>"en", "path"=>"packs/application-f73d5ebd30f5d7783872.js"}
I, [2018-06-21T04:45:39.506015 #1905]  INFO -- : [53cc03e4-c93a-4572-b904-73acf7f9415e]   Rendering application.html.erb
I, [2018-06-21T04:45:39.507447 #1905]  INFO -- : [53cc03e4-c93a-4572-b904-73acf7f9415e]   Rendered application.html.erb (1.3ms)
I, [2018-06-21T04:45:39.507770 #1905]  INFO -- : [53cc03e4-c93a-4572-b904-73acf7f9415e] Completed 200 OK in 2ms (Views: 2.0ms)

```

**Comment by gbarillot** [comment]
Did you try to emulate production env. on your machine? If so, you're missing some steps, and especially the Webpack compilation step. I must say I never tried to do that, all I know is that it works flawlessly if you use Capistrano. I Also saw it working on Heroku out of the box. 
Anyway, that's interesting, I'll add some notes about production deploys in the next few days. Keep us in touch if you have some updates on your side.

**Comment by EnziinSystem** [comment]
I will wait for news from you.

Before deploying to the real server, I usually deploying to docker in production mode.

**Comment by gbarillot** [comment]
Ok, I understand. I'll try to update the Readme as well as the Blog post this week-end.

**Comment by gbarillot** [comment]
Puma issue, found the answer here : [https://github.com/puma/puma/issues/56](https://github.com/puma/puma/issues/56), you have to start Puma like this : 

    RACK_ENV=production bundle exec puma -p 3000

(use RACK_ENV instead of RAILS_ENV) Aside from that, all you did previously was fine, no need to add extra compilation steps for Webpack, since it is included in the "rake asset:precompile" process. 

Just be careful with ActionCable though, I think you have to setup a Redis instance on your machine if you need Websockets to work on production. Nonetheless, this is out of the scope for this simple demo, and it's more generally related to Rails setup IMHO.

**Comment by EnziinSystem** [comment]
Please reopen the issue.

The problem not solved.

I ran commands:
```
RAILS_ENV=production bundle exec rake db:migrate

RAILS_ENV=production bundle exec rake db:seed

RAILS_ENV=production NODE_ENV=production bundle exec rails assets:precompile

RAILS_ENV=production bundle exec puma -p 3000
```
Goto home page http://localhost:3000/

Still errors:
```
I, [2018-06-24T08:48:46.039304 #1035]  INFO -- : [a2d13c4d-dff0-412f-87ed-74bddf9c7272] Started GET "/" for 172.17.0.1 at 2018-06-24 08:48:46 +0000
I, [2018-06-24T08:48:46.047174 #1035]  INFO -- : [a2d13c4d-dff0-412f-87ed-74bddf9c7272] Processing by ApplicationController#index as HTML
I, [2018-06-24T08:48:46.047286 #1035]  INFO -- : [a2d13c4d-dff0-412f-87ed-74bddf9c7272]   Parameters: {"locale"=>"en"}
I, [2018-06-24T08:48:46.050716 #1035]  INFO -- : [a2d13c4d-dff0-412f-87ed-74bddf9c7272]   Rendering application.html.erb
I, [2018-06-24T08:48:46.058024 #1035]  INFO -- : [a2d13c4d-dff0-412f-87ed-74bddf9c7272]   Rendered application.html.erb (7.2ms)
I, [2018-06-24T08:48:46.058312 #1035]  INFO -- : [a2d13c4d-dff0-412f-87ed-74bddf9c7272] Completed 200 OK in 11ms (Views: 10.6ms)
I, [2018-06-24T08:48:46.144366 #1035]  INFO -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9] Started GET "/assets/application-a7d87bae96496b796910b3d5c577d6119212011646d1bab4cde0d7d614130355.css" for 172.17.0.1 at 2018-06-24 08:48:46 +0000
I, [2018-06-24T08:48:46.145766 #1035]  INFO -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9] Processing by ApplicationController#index as CSS
I, [2018-06-24T08:48:46.146025 #1035]  INFO -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9]   Parameters: {"locale"=>"en", "path"=>"assets/application-a7d87bae96496b796910b3d5c577d6119212011646d1bab4cde0d7d614130355.css"}
I, [2018-06-24T08:48:46.147903 #1035]  INFO -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9] Completed 500 Internal Server Error in 2ms
F, [2018-06-24T08:48:46.149124 #1035] FATAL -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9]   
F, [2018-06-24T08:48:46.149213 #1035] FATAL -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9] ActionView::MissingTemplate (Missing template /application with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/home/developer/websites/vue-demo/rails-vue-demo-app/app/views"
  * "/usr/local/rvm/gems/ruby-2.5.1/gems/devise-4.4.3/app/views"
  * "/usr/local/rvm/gems/ruby-2.5.1/gems/kaminari-core-1.1.1/app/views"
):
F, [2018-06-24T08:48:46.149269 #1035] FATAL -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9]   
F, [2018-06-24T08:48:46.149323 #1035] FATAL -- : [26bcb5f9-9e3e-464a-9503-0b24f6b45da9] app/controllers/application_controller.rb:5:in `index'
I, [2018-06-24T08:48:46.148289 #1035]  INFO -- : [8e1daa31-21d8-430c-b07d-72d086aff3f5] Started GET "/packs/application-96bada57c2772a1dd432.js" for 172.17.0.1 at 2018-06-24 08:48:46 +0000
I, [2018-06-24T08:48:46.150381 #1035]  INFO -- : [8e1daa31-21d8-430c-b07d-72d086aff3f5] Processing by ApplicationController#index as */*
I, [2018-06-24T08:48:46.150520 #1035]  INFO -- : [8e1daa31-21d8-430c-b07d-72d086aff3f5]   Parameters: {"locale"=>"en", "path"=>"packs/application-96bada57c2772a1dd432.js"}
I, [2018-06-24T08:48:46.144716 #1035]  INFO -- : [d43c245c-bd07-4817-9b86-c49463fe289a] Started GET "/assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js" for 172.17.0.1 at 2018-06-24 08:48:46 +0000
I, [2018-06-24T08:48:46.156055 #1035]  INFO -- : [d43c245c-bd07-4817-9b86-c49463fe289a] Processing by ApplicationController#index as */*
I, [2018-06-24T08:48:46.156404 #1035]  INFO -- : [d43c245c-bd07-4817-9b86-c49463fe289a]   Parameters: {"locale"=>"en", "path"=>"assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js"}
I, [2018-06-24T08:48:46.160348 #1035]  INFO -- : [8e1daa31-21d8-430c-b07d-72d086aff3f5]   Rendering application.html.erb
I, [2018-06-24T08:48:46.162531 #1035]  INFO -- : [8e1daa31-21d8-430c-b07d-72d086aff3f5]   Rendered application.html.erb (2.0ms)
I, [2018-06-24T08:48:46.163171 #1035]  INFO -- : [8e1daa31-21d8-430c-b07d-72d086aff3f5] Completed 200 OK in 12ms (Views: 12.2ms)
I, [2018-06-24T08:48:46.162879 #1035]  INFO -- : [d43c245c-bd07-4817-9b86-c49463fe289a]   Rendering application.html.erb
I, [2018-06-24T08:48:46.166213 #1035]  INFO -- : [d43c245c-bd07-4817-9b86-c49463fe289a]   Rendered application.html.erb (2.5ms)
I, [2018-06-24T08:48:46.166512 #1035]  INFO -- : [d43c245c-bd07-4817-9b86-c49463fe289a] Completed 200 OK in 10ms (Views: 9.8ms)
I, [2018-06-24T08:48:46.210408 #1035]  INFO -- : [5e254c91-42c4-49d4-941b-5d86fb3c206b] Started GET "/assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js" for 172.17.0.1 at 2018-06-24 08:48:46 +0000
I, [2018-06-24T08:48:46.211203 #1035]  INFO -- : [5e254c91-42c4-49d4-941b-5d86fb3c206b] Processing by ApplicationController#index as */*
I, [2018-06-24T08:48:46.211290 #1035]  INFO -- : [5e254c91-42c4-49d4-941b-5d86fb3c206b]   Parameters: {"locale"=>"en", "path"=>"assets/application-44d17e8bbdf39e95930de94ae5654ce82b543cb205a55ac55b5ca125314d9519.js"}
I, [2018-06-24T08:48:46.211886 #1035]  INFO -- : [5e254c91-42c4-49d4-941b-5d86fb3c206b]   Rendering application.html.erb
I, [2018-06-24T08:48:46.212894 #1035]  INFO -- : [5e254c91-42c4-49d4-941b-5d86fb3c206b]   Rendered application.html.erb (0.9ms)
I, [2018-06-24T08:48:46.213068 #1035]  INFO -- : [5e254c91-42c4-49d4-941b-5d86fb3c206b] Completed 200 OK in 2ms (Views: 1.5ms)
I, [2018-06-24T08:48:46.221522 #1035]  INFO -- : [e0a24631-f1b4-41b5-b7a7-71febdf19ac3] Started GET "/packs/application-96bada57c2772a1dd432.js" for 172.17.0.1 at 2018-06-24 08:48:46 +0000
I, [2018-06-24T08:48:46.222168 #1035]  INFO -- : [e0a24631-f1b4-41b5-b7a7-71febdf19ac3] Processing by ApplicationController#index as */*
I, [2018-06-24T08:48:46.222239 #1035]  INFO -- : [e0a24631-f1b4-41b5-b7a7-71febdf19ac3]   Parameters: {"locale"=>"en", "path"=>"packs/application-96bada57c2772a1dd432.js"}
I, [2018-06-24T08:48:46.222722 #1035]  INFO -- : [e0a24631-f1b4-41b5-b7a7-71febdf19ac3]   Rendering application.html.erb
I, [2018-06-24T08:48:46.223769 #1035]  INFO -- : [e0a24631-f1b4-41b5-b7a7-71febdf19ac3]   Rendered application.html.erb (1.0ms)
I, [2018-06-24T08:48:46.224014 #1035]  INFO -- : [e0a24631-f1b4-41b5-b7a7-71febdf19ac3] Completed 200 OK in 2ms (Views: 1.5ms)
```

**Comment by gbarillot** [comment]
Sorry, but did you take the time to read my answer? Instead of:

    RAILS_ENV=production bundle exec puma -p 3000

Please do:

    RACK_ENV=production bundle exec puma -p 3000

I reproduced the original issue on my machine, and now it works if I use RACK_ENV _instead_ of RAILS_ENV. In all cases, it is a Puma issue, and definitely is not related to the code inside of the demo .

**Comment by EnziinSystem** [comment]
Hi,

In Rails 5.2.0, RACK_ENV replace by RAILS_ENV.

If you open /config/puma.rb:

```
# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }
```
And if run:

`RACK_ENV=production bundle exec puma -p 3000`

Result:

```
RACK_ENV=production bundle exec puma -p 3000
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```
Puma still run in development mode!

We need run the app (Puma) in production. That is why I run RAILS_ENV.
